project: 
  type: website

format:
  revealjs:
    theme: [default, theme.scss]
    css: custom.css
    transition: fade
    background-transition: fade
    highlight-style: arrow
    fontsize: 1.5em
    code-line-numbers: false
    link-external-newwindow: true
    embed-resources: true
code-link: true
execute:
  echo: true
  freeze: auto
  
website: 
  title: ""
  favicon: "figures/favicon.png"
  navbar:
    tools:
    - icon: github
      href: https://github.com/smeekes/R_training
    background: primary
    foreground: light
    logo: "figures/wlogoUM.png"
    logo-href: "https://www.maastrichtuniversity.nl/"
    left:
      - href: index.qmd
        text: "Home"
      - text: "About"
        menu: 
          - text: "About the Training"
            href: about.qmd
          - text: "About the Team"
            href: about-team.qmd

      - text: Sessions
        menu: 
          - text: "Session 1"
            href: Session1.qmd
            target: _blank
          - text: "Session 2"
            href: Session2.qmd
            target: _blank
      - href: files.qmd
        text: "Files"
