project: 
  type: website

format:
  revealjs:
    theme: [default, theme.scss]
    css: custom.css
    transition: fade
    background-transition: fade
    highlight-style: arrow
    fontsize: 1.5em
    code-line-numbers: false
    link-external-newwindow: true
    embed-resources: true
code-link: true
execute:
  echo: true
  freeze: auto